### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ys1382** [ClearKeep/ck-ios#209]
Build issue 1:

<img width="255" alt="215558347-481338ca-37ac-4567-a0f9-f90d6d85d4fc" src="https://user-images.githubusercontent.com/1097496/216213720-95738255-89d5-4cb3-a453-529efe480ea1.png">

If I update pods, the Realm issue goes away. https://github.com/realm/realm-swift/issues/8015 says do this: "pod deintegrate", "pod install", and "pod update". There should be some way to fix this issue in our code.

Build issue 2:

image_2023_01_30T10_28_40_599Z

line 100: Replace
GIDSignIn.sharedInstance.signIn(with: googleSignInConfiguration, presenting: topViewController)

with

GIDSignIn.sharedInstance.signIn(withPresenting: topViewController) { result, error in

==============================
line 102: Replace
guard let idToken = result?.authentication.idToken else { return continuation.resume(returning: .failure(ServerError.unknown)) }

with

guard let idToken = user?.user.idToken?.tokenString else { return continuation.resume(returning: .failure(ServerError.unknown)) }

(google sign in api update new callback object)

===================
line 235: Replace
googleSignInConfiguration = GIDConfiguration(clientID: clientId)

with

GIDSignIn.sharedInstance.configuration = GIDConfiguration(clientID: clientId)
(assign configuration to a different property)

**Comment by EddieLukeAtmey** [comment]
This issue has been fixed in PR #205
