### ISSUE TITLE
Remove manual steps to build

### ISSUE THREAD

**Issue by ys1382** [ClearKeep/ck-ios#210]
The Readme includes manual steps for the proto files. Instead:

put the proto files in a git submodule that all the CK repos use
put the protoc command in the Xcode project build script.
Then the only steps needed to build are:

git clone --recursive
pod install
xcodebuild
You also forgot to mention these steps (which may need to be manual)
$ git clone https://github.com/grpc/grpc-swift
$ cd grpc-swift
$ make plugins
$ cp .build/release/protoc-gen-swift .build/release/protoc-gen-grpc-swift /usr/local/bin

**Comment by EddieLukeAtmey** [comment]
@ys1382 the proto generated swift files are included in the project source code, so we don't need to add a script to generate the proto files every time we clone => Not necessary to add a submodule.

The step you mentioned about grpc-swift, it's already included in the readme file
```
brew install swift-protobuf grpc-swift
mkdir Protobuf
protoc --grpc-swift_out=Protobuf/ --swift_out=proto/ *.proto
```

I'll update the readme a little bit to avoid confusing later.

Assumed that every other tools (rust, cocoapods, ruby) are ready, the only steps needed to build from scratch are:
```
git clone
pod install
```
